feat/tagoio-deploy-url
tago-io/tagoio-cli pull request #16
Opened 2024-08-05 17:40 UTC by mateuscardosodeveloper

2024-08-07 13:56 UTC, cotrin requested changes

2024-08-30 17:36 UTC, cotrin requested changes

2024-08-30 17:36 UTC, cotrin commented on src/commands/analysis/run-analysis.ts
> +  const account = new Account({ token: config.profileToken, region: !process.env.TAGOIO_API ? "usa-1" : "env" });
Run command still has some issues. I tried running "test-analysis.ts" that is attached to an analysis called "test" in TagoIO Deploy. The analysis was correctly placed in external, but the command is trying to use a different analysis in the profile (Bulk Device Create).

<img width="841" alt="image" src="https://github.com/user-attachments/assets/9614778b-efde-406d-91e4-27e53ca351ec">

2024-09-06 20:39 UTC, cotrin reviewed
Need to do:

- update README
- verify at which level the TagoDeployURL should be included (inside each environment or one for all)

2024-09-09 20:03 UTC, vitorfdl approved these changes

2024-09-09 20:03 UTC, merged